---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "Sposea-principal"
    cfSpace: "development"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us21.hana.ondemand.com"
    cfOrg: "sposea-axalta-npr-brightprice"
    cfSpace: "development"
    cfAppName: "app"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: false

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "development"
    credentialsId: "tms-sk"
    customDescription: "app : Business Application"
